# Experiment with bioc build via actions

name: build

on:
  #push:
  #pull_request:
  ##release:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo for Package Status'
        required: true
        default: 'cran'
        type: choice
        options:
          - p3m
          - cran
      jammy:
        description: 'jammy all: {"target":["a","b","c"]}'
        required: true
        default: '{"target":["digest","tint"]}'
        type: string
      noble:
        description: 'noble all: {"target":["a","b","c"]}'
        required: true
        default: '{"target":["digest","tint"]}'
        type: string
      noble_arm:
        description: 'noble arm: {"target":["a","c"]}'
        required: true
        default: '{"target":[""]}'
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: eddelbuettel/gha_r2u_build:noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Default Config and Cache
        run: |
          r -e 'r2u:::.createDefaultConfiguration()'
      - name: Fetch Updated Config
        uses: actions/checkout@v4
        with:
          repository: eddelbuettel/r2u-config
          path: r2u-config
      - name: Copy Updated Config
        run: cp -vax r2u-config/* ~/.local/share/R/r2u
      - name: Create Cache
        run: |
          r -e 'r2u:::.loadDB()'
          r -e 'r2u:::.loadAP(repo="${{ inputs.repo }}")'
          r -e 'r2u:::.allBuilds("jammy")'
          r -e 'r2u:::.allBuilds("noble")'
      - name: Upload Config
        uses: actions/upload-artifact@v6
        with:
          name: r2u_config
          path: ~/.local/share/R/r2u
    
  build_jammy:
    needs: setup
    if: ${{ inputs.jammy != '{"target":[""]}' }}
    name: "build (jammy)"
    strategy:
      fail-fast: false
    uses: eddelbuettel/r2u-builder/.github/workflows/workflow_build.yaml@main
    with:
      dist: "jammy"
      targets: ${{ inputs.jammy }}
    secrets: inherit
    
  build_noble:
    needs: setup
    if: ${{ inputs.noble != '{"target":[""]}' }}
    name: "build (noble)"
    strategy:
      fail-fast: false
    uses: eddelbuettel/r2u-builder/.github/workflows/workflow_build.yaml@main
    with:
      dist: "noble"
      targets: ${{ inputs.noble }}
    secrets: inherit
    
  build_noble_arm:
    needs: setup
    if: ${{ inputs.noble_arm != '{"target":[""]}' }}
    name: "build (noble, arm)"
    strategy:
      fail-fast: false
    uses: eddelbuettel/r2u-builder/.github/workflows/workflow_build.yaml@main
    with:
      dist: "noble"
      arch: "-arm"
      targets: ${{ inputs.noble_arm }}
    secrets: inherit
          
          
